# Dependencies
markdown:         kramdown
kramdown: 
  input: GFM
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Michael Krautzberger
tagline:          'Informationen für Studium und Praxis'
description:      'Prof. Dr. Michael Krautzberger'
url:              http://www.krautzberger.info

author:
  name:           'Michael Krautzberger'
  url:            https://www.krautzberger.info

paginate:         5